server:
  port: 8092
  servlet:
    context-path: /currency

spring:
  application:
    name: currency-exchange
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    table: flyway_exchange_schema_history
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  swagger-ui:
    path: /swagger-ui.html

external:
  api:
    url: http://api.currencylayer.com
    access_key: 2362a6119e55364b274a49c46830983f